### ISSUE TITLE
Ошибка на арене

### ISSUE THREAD

**Issue by dvachevskyi** [eigenein/bestmobabot#14]
```
Sep 29 13:17:44 (bestmobabot.scheduler:83) [I] Running attack_normal_arena scheduled at Sep 29 13:17:44 UTC+03:00…
Sep 29 13:17:44 (bestmobabot.bot:354) [I] Loading model…
Sep 29 13:17:44 (bestmobabot.api:210) [I] #8: heroGetAll({}) in 5.0 seconds…
Sep 29 13:17:50 (bestmobabot.api:210) [I] #9: userGetInfo({}) in 7.1 seconds…
Sep 29 13:17:57 (bestmobabot.api:210) [I] #10: arenaFindEnemies({}) in 9.8 seconds…
Sep 29 13:18:08 (bestmobabot.scheduler:112) [C] Uncaught error.
Traceback (most recent call last):
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\scheduler.py", line 98, in execute
    next_run_at = task.execute()
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\bot.py", line 416, in attack_normal_arena
    finalise=lambda: None,
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\bot.py", line 372, in attack_any_arena
    solution = make_solver(model, heroes).solve()
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\arena.py", line 135, in solve
    return secretary_max(self.yield_solutions(), self.max_iterations, early_stop=self.early_stop)
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\itertools_.py", line 53, in secretary_max
    for i, item in enumerate(items, start=1):
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\arena.py", line 146, in yield_solutions
    yield max(self.solve_enemy_cached(enemy) for enemy in enemies)
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\arena.py", line 146, in <genexpr>
    yield max(self.solve_enemy_cached(enemy) for enemy in enemies)
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\arena.py", line 185, in solve_enemy_cached
    solution = self.solve_enemy(enemy)
  File "C:\Users\Waff\Downloads\bestmobabot-master\bestmobabot-master\bestmobabot\arena.py", line 219, in solve_enemy
    for group_1, group_2 in combinations(groups, 2)  # select two groups to interchange heroes in
  File "C:\Users\Waff\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

**Comment by eigenein** [comment]
Спасибо за репорт. Это возникло однократно или происходит постоянно?

**Comment by dvachevskyi** [comment]
Постоянно

**Comment by eigenein** [comment]
А запустите, пожалуйста, бота с флагом `-vv` и скиньте тот же самый кусок лога.

И еще я должен уточнить, сколько у вас героев?
